// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEN3wZADyMlDigWZXIfaZBa1siay1dnJU',
    appId: '1:246594451367:web:a89bc765af0786c82ca882',
    messagingSenderId: '246594451367',
    projectId: 'atividade-listatarefas',
    authDomain: 'atividade-listatarefas.firebaseapp.com',
    storageBucket: 'atividade-listatarefas.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWKPPq2FOEUngEPsIM1e2ga0Fp1rNcdQU',
    appId: '1:246594451367:android:4ae7a8b6c80203592ca882',
    messagingSenderId: '246594451367',
    projectId: 'atividade-listatarefas',
    storageBucket: 'atividade-listatarefas.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCv-dCM1fSrlIGOYo-LcmEBcYaM3AyXGdQ',
    appId: '1:246594451367:ios:7cb27c9a76637c072ca882',
    messagingSenderId: '246594451367',
    projectId: 'atividade-listatarefas',
    storageBucket: 'atividade-listatarefas.firebasestorage.app',
    iosBundleId: 'com.example.appFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCv-dCM1fSrlIGOYo-LcmEBcYaM3AyXGdQ',
    appId: '1:246594451367:ios:7cb27c9a76637c072ca882',
    messagingSenderId: '246594451367',
    projectId: 'atividade-listatarefas',
    storageBucket: 'atividade-listatarefas.firebasestorage.app',
    iosBundleId: 'com.example.appFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDEN3wZADyMlDigWZXIfaZBa1siay1dnJU',
    appId: '1:246594451367:web:721e3c31ab6127f12ca882',
    messagingSenderId: '246594451367',
    projectId: 'atividade-listatarefas',
    authDomain: 'atividade-listatarefas.firebaseapp.com',
    storageBucket: 'atividade-listatarefas.firebasestorage.app',
  );
}
